spring:
  datasource:
    url: jdbc:mysql://119.91.204.244:3305/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 12345

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      field-strategy: not_null
  mapper-locations: classpath:mapper/*.xml
